'use strict';
/**
 * build-article.js — ARTICLE bundler.
 *
 * Inlines the parsed article content + design tokens + the small component set
 * the article needs + ArticleApp into a single JSX bundle, mirroring the
 * proposal bundler (src/utils/build.js) but for the long-form article app.
 *
 * REUSES (DRY) the proposal bundler's shared helpers so theme/accent
 * build-time injection and ESM stripping live in ONE place:
 *   - extractDesignTokensCode  → inlines design-tokens.js with PD_THEME /
 *                                PD_ACCENT injected as build-time LITERALS
 *                                (never a runtime process.env read in the
 *                                browser bundle → never renders blank).
 *   - stripModuleSyntax        → strips import/export for inline bundling.
 *   - readDesignTokens, SRC_DIR
 *
 * Reads:  PD_ARTICLE_CONTENT_OUT (article content module written by parse-article.js)
 * Writes: PD_JSX_OUT             (the JSX bundle; a per-invocation temp path)
 *
 * API:  buildArticle()
 * CLI:  PD_ARTICLE_CONTENT_OUT=… PD_JSX_OUT=… node scripts/build-article.js
 */

const fs   = require('fs');
const path = require('path');

const {
  extractDesignTokensCode,
  stripModuleSyntax,
  readDesignTokens,
  SRC_DIR,
} = require('../src/utils/build.js');

const DIST_DIR = path.resolve(__dirname, '../dist');

function readFileOrDie(filePath) {
  if (!fs.existsSync(filePath)) {
    console.error(`build-article: file not found: ${filePath}`);
    process.exit(1);
  }
  return fs.readFileSync(filePath, 'utf-8');
}

// Components the article renders. Section MUST be first (defines the shared
// useInView hook that Table relies on). RichText is referenced by Section,
// Table, and ArticleApp. ChartsSVG MUST precede Chart (Chart imports its SVG
// primitives). Charts are now first-class in the article format (Task 11).
const ARTICLE_COMPONENTS = ['Section', 'RichText', 'Table', 'ReadingProgress', 'ChartsSVG', 'Chart', 'DiagramError', 'QuadrantChart', 'FlowDiagram', 'MermaidFigure'];

function buildArticle() {
  const outputFile = process.env.PD_JSX_OUT || path.join(DIST_DIR, 'Article.jsx');
  const contentPath = process.env.PD_ARTICLE_CONTENT_OUT;
  if (!contentPath) {
    console.error('build-article: PD_ARTICLE_CONTENT_OUT env var is required (article content module)');
    process.exit(1);
  }

  console.log('Building article bundle...\n');

  // Only create DIST_DIR when actually writing there (the orchestrator writes a temp path).
  if (outputFile.startsWith(DIST_DIR) && !fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
  }

  // 1. Article content (generated by parse-article.js)
  console.log('  Reading article content...');
  let content = readFileOrDie(contentPath);
  content = stripModuleSyntax(content);

  // 2. Design tokens — with BUILD-TIME theme/accent injection (shared helper).
  console.log('  Reading design-tokens (with theme injection)...');
  const designTokensCode = extractDesignTokensCode(readDesignTokens());

  // 3. Components (Section first for useInView)
  const componentCode = ARTICLE_COMPONENTS.map((name) => {
    console.log(`  Reading ${name}...`);
    return stripModuleSyntax(readFileOrDie(path.join(SRC_DIR, 'components', `${name}.jsx`)));
  }).join('\n\n');

  // 4. ArticleApp
  console.log('  Reading ArticleApp...');
  const app = stripModuleSyntax(readFileOrDie(path.join(SRC_DIR, 'ArticleApp.jsx')));

  // 5. Assemble bundle (same shape as the proposal bundle: ESM import header +
  //    `export default App`, both stripped later by the wrapper for the browser).
  const bundle = `/**
 * Portable Document — Article Bundle
 * Generated: ${new Date().toISOString()}
 *
 * Auto-generated. Do not edit directly.
 */
import React, { useState, useEffect, useRef, useCallback, useMemo } from 'react';

// ============================================================================
// ARTICLE CONTENT DATA
// ============================================================================

${content}

// ============================================================================
// DESIGN TOKENS (build-time theme injection)
// ============================================================================

${designTokensCode}

// ============================================================================
// COMPONENTS
// ============================================================================

${componentCode}

// ============================================================================
// ARTICLE APPLICATION
// ============================================================================

${app}

export default App;
`;

  fs.writeFileSync(outputFile, bundle);
  console.log(`\n✓ Article bundle written to ${outputFile}`);
  console.log(`  Size: ${(fs.statSync(outputFile).size / 1024).toFixed(1)} KB`);
}

module.exports = { buildArticle };

if (require.main === module) buildArticle();
