'use strict';
/**
 * build-slides.js — SLIDE DECK bundler.
 *
 * Inlines the parsed slides content + design tokens (with build-time theme
 * injection) + the minimal component set SlideDeck needs + SlideDeck.jsx into a
 * single JSX bundle, mirroring the article bundler (build-article.js).
 *
 * REUSES (DRY) the proposal + article bundlers' shared helpers from build.js:
 *   - extractDesignTokensCode  → injects ACTIVE_THEME as a build-time LITERAL
 *                                (no runtime process.env in the browser bundle).
 *   - stripModuleSyntax        → strips import/export for inline bundling.
 *   - readDesignTokens, SRC_DIR
 *
 * Reads:  PD_SLIDES_CONTENT_OUT (slide content module written by parse-slides.js)
 * Writes: PD_JSX_OUT            (the JSX bundle; a per-invocation temp path)
 *
 * API:  buildSlides()
 * CLI:  PD_SLIDES_CONTENT_OUT=… PD_JSX_OUT=… node scripts/build-slides.js
 */

const fs   = require('fs');
const path = require('path');

const {
  extractDesignTokensCode,
  stripModuleSyntax,
  readDesignTokens,
  SRC_DIR,
} = require('../src/utils/build.js');

const DIST_DIR = path.resolve(__dirname, '../dist');

function readFileOrDie(filePath) {
  if (!fs.existsSync(filePath)) {
    console.error(`build-slides: file not found: ${filePath}`);
    process.exit(1);
  }
  return fs.readFileSync(filePath, 'utf-8');
}

// Components SlideDeck renders. Section MUST be first (defines Paragraph,
// BulletList, and the useInView hook that Table may rely on).
const SLIDE_COMPONENTS = ['Section', 'RichText', 'Table', 'ChartsSVG', 'Chart', 'DiagramError', 'QuadrantChart', 'FlowDiagram', 'MermaidFigure'];

function buildSlides() {
  const outputFile  = process.env.PD_JSX_OUT || path.join(DIST_DIR, 'SlideDeck.jsx');
  const contentPath = process.env.PD_SLIDES_CONTENT_OUT;
  if (!contentPath) {
    console.error('build-slides: PD_SLIDES_CONTENT_OUT env var is required (slides content module)');
    process.exit(1);
  }

  console.log('Building slide deck bundle...\n');

  // Only create DIST_DIR when actually writing there
  if (outputFile.startsWith(DIST_DIR) && !fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
  }

  // 1. Slide content (generated by parse-slides.js)
  console.log('  Reading slides content...');
  let content = readFileOrDie(contentPath);
  content = stripModuleSyntax(content);

  // 2. Design tokens — with BUILD-TIME theme/accent injection (shared helper).
  console.log('  Reading design-tokens (with theme injection)...');
  const designTokensCode = extractDesignTokensCode(readDesignTokens());

  // 3. Components (Section first — defines Paragraph, BulletList, useInView)
  const componentCode = SLIDE_COMPONENTS.map((name) => {
    console.log(`  Reading ${name}...`);
    return stripModuleSyntax(readFileOrDie(path.join(SRC_DIR, 'components', `${name}.jsx`)));
  }).join('\n\n');

  // 4. SlideDeck app
  console.log('  Reading SlideDeck...');
  const app = stripModuleSyntax(readFileOrDie(path.join(SRC_DIR, 'SlideDeck.jsx')));

  // 5. Assemble bundle (same shape as proposal + article bundles)
  const bundle = `/**
 * Portable Document — Slide Deck Bundle
 * Generated: ${new Date().toISOString()}
 *
 * Auto-generated. Do not edit directly.
 */
import React, { useState, useEffect, useRef, useCallback, useMemo } from 'react';

// ============================================================================
// SLIDES CONTENT DATA
// ============================================================================

${content}

// ============================================================================
// DESIGN TOKENS (build-time theme injection)
// ============================================================================

${designTokensCode}

// ============================================================================
// COMPONENTS
// ============================================================================

${componentCode}

// ============================================================================
// SLIDE DECK APPLICATION
// ============================================================================

${app}

export default App;
`;

  fs.writeFileSync(outputFile, bundle);
  console.log(`\n✓ Slide deck bundle written to ${outputFile}`);
  console.log(`  Size: ${(fs.statSync(outputFile).size / 1024).toFixed(1)} KB`);
}

module.exports = { buildSlides };

if (require.main === module) buildSlides();
